# Generated by Django 4.1.1 on 2022-09-22 16:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fitapp', '0004_measurement_user_alter_customer_measurement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='measurement',
        ),
        migrations.RemoveField(
            model_name='measurement',
            name='user',
        ),
        migrations.AddField(
            model_name='measurement',
            name='customer',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='fitapp.customer'),
        ),
    ]
