# Generated by Django 4.1.1 on 2022-09-22 18:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fitapp', '0005_remove_customer_measurement_remove_measurement_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measurement',
            name='customer',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='customer', to='fitapp.customer'),
        ),
    ]
