# Generated by Django 4.1.1 on 2022-09-23 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitapp', '0008_customer_created_on_measurement_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
