# Generated by Django 4.1.1 on 2022-09-25 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitapp', '0009_alter_customer_created_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='age',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='height',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
