# Generated by Django 4.1.1 on 2022-10-01 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fitapp', '0022_alter_measurement_managers_alter_media_managers'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='measurement',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='media',
            managers=[
            ],
        ),
    ]
